- name: Prepare EDA Objects
  ansible.builtin.include_tasks: prepare.yaml
  when: installation_type is defined and installation_type == "ocp"

- name: Deploy EDA Objects
  ansible.builtin.include_tasks:
    file: deploy.yaml
    apply:
      environment:
        EDA_HOST: "{{ aap_host }}"
        EDA_USERNAME: "{{ aap_username }}"
        EDA_PASSWORD: "{{ aap_password }}"
        EDA_VERIFY_SSL: "false"
