- name: Prepare Controller Objects
  ansible.builtin.include_tasks: prepare.yaml
  when: installation_type is defined and installation_type == "ocp"

- name: Deploy Controller Objects
  ansible.builtin.include_tasks:
    file: deploy.yaml
    apply:
      environment:
        CONTROLLER_HOST: "{{ aap_host }}"
        CONTROLLER_USERNAME: "{{ aap_username }}"
        CONTROLLER_PASSWORD: "{{ aap_password }}"
        CONTROLLER_VERIFY_SSL: "false"
        GATEWAY_HOSTNAME: "{{ aap_host }}"
        GATEWAY_USERNAME: "{{ aap_username }}"
        GATEWAY_PASSWORD: "{{ aap_password }}"
        GATEWAY_VERIFY_SSL: "false"
